/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as PolitiqueRouteImport } from './routes/politique'
import { Route as EnvironnementRouteImport } from './routes/environnement'
import { Route as EconomieRouteImport } from './routes/economie'
import { Route as CultureRouteImport } from './routes/culture'
import { Route as AProposRouteImport } from './routes/a-propos'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ArticleSlugRouteImport } from './routes/article.$slug'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const PolitiqueRoute = PolitiqueRouteImport.update({
  id: '/politique',
  path: '/politique',
  getParentRoute: () => rootRouteImport,
} as any)
const EnvironnementRoute = EnvironnementRouteImport.update({
  id: '/environnement',
  path: '/environnement',
  getParentRoute: () => rootRouteImport,
} as any)
const EconomieRoute = EconomieRouteImport.update({
  id: '/economie',
  path: '/economie',
  getParentRoute: () => rootRouteImport,
} as any)
const CultureRoute = CultureRouteImport.update({
  id: '/culture',
  path: '/culture',
  getParentRoute: () => rootRouteImport,
} as any)
const AProposRoute = AProposRouteImport.update({
  id: '/a-propos',
  path: '/a-propos',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticleSlugRoute = ArticleSlugRouteImport.update({
  id: '/article/$slug',
  path: '/article/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/culture': typeof CultureRoute
  '/economie': typeof EconomieRoute
  '/environnement': typeof EnvironnementRoute
  '/politique': typeof PolitiqueRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/article/$slug': typeof ArticleSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/culture': typeof CultureRoute
  '/economie': typeof EconomieRoute
  '/environnement': typeof EnvironnementRoute
  '/politique': typeof PolitiqueRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/article/$slug': typeof ArticleSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/culture': typeof CultureRoute
  '/economie': typeof EconomieRoute
  '/environnement': typeof EnvironnementRoute
  '/politique': typeof PolitiqueRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/article/$slug': typeof ArticleSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/a-propos'
    | '/culture'
    | '/economie'
    | '/environnement'
    | '/politique'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/article/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/a-propos'
    | '/culture'
    | '/economie'
    | '/environnement'
    | '/politique'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/article/$slug'
  id:
    | '__root__'
    | '/'
    | '/a-propos'
    | '/culture'
    | '/economie'
    | '/environnement'
    | '/politique'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/article/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AProposRoute: typeof AProposRoute
  CultureRoute: typeof CultureRoute
  EconomieRoute: typeof EconomieRoute
  EnvironnementRoute: typeof EnvironnementRoute
  PolitiqueRoute: typeof PolitiqueRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ArticleSlugRoute: typeof ArticleSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/politique': {
      id: '/politique'
      path: '/politique'
      fullPath: '/politique'
      preLoaderRoute: typeof PolitiqueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/environnement': {
      id: '/environnement'
      path: '/environnement'
      fullPath: '/environnement'
      preLoaderRoute: typeof EnvironnementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/economie': {
      id: '/economie'
      path: '/economie'
      fullPath: '/economie'
      preLoaderRoute: typeof EconomieRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/culture': {
      id: '/culture'
      path: '/culture'
      fullPath: '/culture'
      preLoaderRoute: typeof CultureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/a-propos': {
      id: '/a-propos'
      path: '/a-propos'
      fullPath: '/a-propos'
      preLoaderRoute: typeof AProposRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/article/$slug': {
      id: '/article/$slug'
      path: '/article/$slug'
      fullPath: '/article/$slug'
      preLoaderRoute: typeof ArticleSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AProposRoute: AProposRoute,
  CultureRoute: CultureRoute,
  EconomieRoute: EconomieRoute,
  EnvironnementRoute: EnvironnementRoute,
  PolitiqueRoute: PolitiqueRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ArticleSlugRoute: ArticleSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
